### ISSUE TITLE
Provide BOM and Gerbers for Model T

### ISSUE THREAD

**Issue by nhorvath** [trezor/trezor-hardware#13]
Can you please provide similar resources for the model t as you have for the one? Thanks!

**Comment by diimdeep** [comment]
Mentioned here https://www.youtube.com/watch?v=ggeCYry3gTw

**Comment by specs32** [comment]
> Can you please provide similar resources for the model t as you have for the one? Thanks!

BOM is here https://github.com/trezor/trezor-firmware/blob/master/docs/hardware/model-t/index.md

**Comment by prusnak** [comment]
I just copied the `bom.txt` and other files from the trezor-firmware repo to this repo.

We don't provide the Gerber files at the moment, only Eagle files - so it should be trivial to generate the Gerbers, but I'll have a look at this later.

**Comment by nhorvath** [comment]
The free version of eagle only supports 2 layers.

**Comment by prusnak** [comment]
I added the KiCad files (Eagle imports) to the Repo:

https://github.com/trezor/trezor-hardware/tree/master/electronics/trezor_model_t/kicad
and
https://github.com/trezor/trezor-hardware/tree/master/electronics/trezor_one/kicad

Feel free to send improvements to these.

I am not going to add Gerber files, because it should be trivial to export these from KiCad.
